import type { ComponentDoc } from "../types";
import { props } from "./props";
import { FlexPreview } from "./preview";
import { FlexExample } from "./example";

const doc: ComponentDoc = {
    id: "flex",
    name: "Flex",
    package: "@fremtind/jokul/flex",
    category: "Layout",
    status: "stable",
    complexity: { use: "easy", maintenance: "easy" },
    description: {
        short: "Den primære layout-primitiven i Jøkul.",
        long: "Flex er den primære layout-primitiven i Jøkul. Den lar deg bygge flexbox-layouts med Jøkuls spacing-skala for gap, uten å skrive CSS. Komponenten rendres som div som standard, men kan rendres som et hvilket som helst HTML-element via as-proppen.",
    },
    relationships: {
        related: [{ id: "button", description: "Wrapper flere Button-elementer i Flex for å kontrollere mellomrom og justering i en verktøylinje eller skjemafot." }, { id: "tag", description: "Bruk Flex for å legge ut en rad med Tags med konsistent mellomrom og linjebryting." }],
    },
    preview: <FlexPreview />,
    example: (props) => <FlexExample {...props} />,
    exampleControlsConfig: {
        include: [
            "direction",
            "gap",
            "wrap",
            "alignItems",
            "justifyContent",
            "alignContent",
            "textAlign",
            "layout",
            "center",
            "fill",
            "inline",
            "as",
            "asChild",
            "demo.itemCount",
            "demo.containerHeight",
            "demo.useResponsive",
            "demo.gapResponsive",
            "demo.layoutResponsive",
        ],
        order: [
            "direction",
            "gap",
            "wrap",
            "alignItems",
            "justifyContent",
            "alignContent",
            "textAlign",
            "layout",
            "center",
            "fill",
            "inline",
            "as",
            "asChild",
            "demo.itemCount",
            "demo.containerHeight",
            "demo.useResponsive",
            "demo.gapResponsive",
            "demo.layoutResponsive",
        ],
        overrides: {
            gap: {
                kind: "select",
                options: ["none", "2xs", "xs", "s", "m", "l", "xl", "2xl", "16", "24", "40"],
                defaultValue: "m",
            },
            wrap: { kind: "select", options: ["nowrap", "wrap", "reverse"], defaultValue: "nowrap" },
            alignItems: {
                kind: "select",
                options: ["normal", "start", "center", "end", "baseline", "stretch"],
                defaultValue: "stretch",
            },
            alignContent: {
                kind: "select",
                options: ["normal", "start", "center", "end", "stretch", "baseline", "space-between", "space-around", "space-evenly"],
                defaultValue: "normal",
            },
            justifyContent: {
                kind: "select",
                options: ["normal", "start", "center", "end", "space-between", "space-around", "space-evenly"],
                defaultValue: "start",
            },
            textAlign: { kind: "select", options: ["left", "center", "right"], defaultValue: "left" },
            layout: {
                kind: "select",
                options: ["auto", "1", "2", "3", "4", "6", "4.8", "8.4", "2.10", "10.2", "3.9", "9.3", "5.7", "7.5"],
                defaultValue: "auto",
            },
            center: {
                kind: "select",
                options: [
                    { label: "Av", value: false },
                    { label: "På", value: true },
                    "m",
                    "l",
                    "xl",
                    "2xl",
                ],
                defaultValue: false,
            },
            fill: { kind: "boolean", defaultValue: false },
            inline: { kind: "boolean", defaultValue: false },
            as: {
                kind: "select",
                options: ["div", "section", "article", "nav"],
                defaultValue: "div",
                visibleWhen: { name: "asChild", value: false },
            },
            asChild: { kind: "boolean", defaultValue: false },
            "demo.itemCount": { kind: "number", defaultValue: 12, min: 4, max: 24, step: 1 },
            "demo.containerHeight": { kind: "number", defaultValue: 16, min: 8, max: 32, step: 1 },
            "demo.useResponsive": { kind: "boolean", defaultValue: false },
            "demo.gapResponsive": {
                kind: "json",
                defaultValue: '{"small":"s","large":"l"}',
                keyReadOnly: true,
                valueOptions: ["none", "2xs", "xs", "s", "m", "l", "xl", "2xl", "0", "2", "4", "8", "12", "16", "20", "24", "28", "32", "40", "48", "56", "64", "72", "80", "104", "168", "s m"],
                visibleWhen: { name: "demo.useResponsive", value: true },
            },
            "demo.layoutResponsive": {
                kind: "json",
                defaultValue: '{"small":"1","large":"3"}',
                keyReadOnly: true,
                valueOptions: ["auto", "1", "2", "3", "4", "6", "4.8", "8.4", "2.10", "10.2", "3.9", "9.3", "5.7", "7.5"],
                visibleWhen: { name: "demo.useResponsive", value: true },
            },
        },
    },

    props,
};

export default doc;
