import type {PropDef} from "../types";

export const props: PropDef[] = [
    {
        name: "fileName",
        type: "string",
        required: true,
        source: "custom",
        status: "stable",
        description: "Filnavnet som vises til brukeren.",
    },
    {
        name: "fileType",
        type: "string",
        required: true,
        source: "custom",
        status: "stable",
        description: "Filtype eller MIME-type. Brukes blant annet til å avgjøre om komponenten kan vise miniatyr.",
    },
    {
        name: "fileSize",
        type: "number",
        required: true,
        source: "custom",
        status: "stable",
        description: "Filstørrelse i bytes, som formatteres for visning.",
    },
    {
        name: "path",
        type: "string",
        required: false,
        source: "custom",
        status: "stable",
        description: "Lenke til filen. Når den er satt, blir filnavnet klikkbart.",
    },
    {
        name: "errorLabel",
        type: "string",
        required: false,
        source: "custom",
        status: "stable",
        default: '"Feil"',
        description: "Tekst som vises når filen er i feiltilstand.",
    },
    {
        name: "state",
        type: '"error" | "loading"',
        required: false,
        source: "custom",
        status: "stable",
        description: "Viser om filen fortsatt lastes opp eller har feilet.",
    },
    {
        name: "variant",
        type: '"list" | "card"',
        required: false,
        source: "custom",
        status: "stable",
        default: '"list"',
        description: "Velg mellom kompakt listevisning og kortvisning.",
    },
    {
        name: "file",
        type: "File",
        required: false,
        source: "custom",
        status: "stable",
        description: "Det underliggende File-objektet, brukt blant annet for lokale forhåndsvisninger av bilder.",
    },
    {
        name: "onRemove",
        type: "(e: React.MouseEvent<HTMLButtonElement>) => void",
        required: false,
        source: "custom",
        status: "stable",
        description: "Viser en fjern-knapp og kalles når brukeren vil fjerne filen fra listen.",
    },
    {
        name: "className",
        type: "string",
        required: false,
        source: "react",
        status: "stable",
        description: "Ekstra CSS-klasser på rotnoden.",
    },
];
